### PR TITLE
Updated readme to new instructions for Mac OS X and new name (really!)

### PR DESCRIPTION
**Pull request by dcwalk**
Hiya @agamba can you review?

Closed the old one (#62) , this points toward prerelease now

(at least) two remaining issues are:
- [ ] confirm about 'completely removing data' with Mac OS X, data stays in the application support folder.... do we want to account for this?
- [x] add in instructions for installing/running using Linux (thanks @vid)

### CODE REVIEW

**Comment by dcwalk** [comment]
@vid and @agamba  Sorry, git meltdown today, think I've got it, anything further will go to pre-release.

**Comment by agamba** [comment]
Hi Dawn, 
Can you elaborate on this "confirm about 'completely removing data' with Mac OS X, data stays in the application support folder.... do we want to account for this?"
I'm not aware of this. What data is being saved in application support folder?

**Comment by dcwalk** [comment]
Hi @agamba here is what is in mine:
screen shot 2015-12-02 at 4 01 55 pm

Generally I think Application Support files are caches and config files I think? 
@vid could (obviously) speak better to this.

**Comment by vid** [comment]
Sorry, I don't know much about Macs. What I see in your screenshot is not part of the app.

**Comment by dcwalk** [comment]
Yeah @vid, it is generated by installing/using the client...

Sorry, my understanding was that this data creation is to some degree determined behaviour based on how something is developed.

**Comment by dcwalk** [comment]
Updated to add separate license file as well.

**Comment by agamba** [comment]
Hi Dawn, I'm not sure either of where are the Application Support files you point to. I think we should do a further inspection to replicate what say. In my end, I don't seem to have those files when the IXmpasClient is running or submitting data to the server. Please add a full path where you see those in your system.

**Comment by dcwalk** [comment]
@agamba the path is: ```~/Library/Application Support/``` to see that folder.

**Comment by dcwalk** [comment]
@agamba just checking in... would you like to use any of the material in this branch or should I close this pull request?

**Pull request merged**
