### PR TITLE
Close existing server

### PR DESCRIPTION
**Pull request by vid**

### CODE REVIEW

**Comment by Andrew-Clement** [comment]
Thanks David for your very quick and helpful response. @agamba @colinmccann let me know when this is merged ... and I'll give it a test.

**Comment by vid** [comment]
Are you going to merge this one?

**Comment by Andrew-Clement** [comment]
Thanks for this reminder David.  

@agamba, any reason not to proceed with this?

**Comment by agamba** [comment]
I have merged the code added by David and will now proceed to test the code in all OS (Mac, unix, win) in order to create new distribution packages

**Comment by Andrew-Clement** [comment]
Thanks Anto, good to see this.

I notice that github is pushing 'continuous integration providers'. I wonder whether we currently use any of these?  Would doing so be helpful to us?

**Pull request merged**
